node_id = "dtn://go1/"
log_level = "Debug"

[Store]
path = "/tmp/dtn_go1_store"

[Routing]
algorithm = "epidemic"

[Agents]
[Agents.REST]
address = ":8080"
[Agents.UNIX]
address = "/tmp/dtnd_go1.socket"

[[Listener]]
type = "mtcp"
address = ":35037"

[Cron]
dispatch = "10s"
