nodeid = "rs2"
debug = true
beacon-period = true

webport = 3000
unixsocket = "/tmp/dtnd_rs2.socket"
workdir = "/tmp/dtn_rs2_store"
db = "mem"

[routing]
strategy = "epidemic"

[core]
janitor = "10s"

[discovery]
interval = "2s"
peer-timeout = "20s"
port = 3003

[convergencylayers]
cla.0.id = "mtcp"
cla.0.port = 16163

[endpoints]
local.0 = "in"
